//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gift
    {
        public int IdPresent { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public Nullable<System.DateTime> DateEntry { get; set; }
        public byte[] PresentIMG { get; set; }
        public string PresentLink { get; set; }
        public string UserEmail { get; set; }
        public string GiftedPersonEmail { get; set; }
        public string CodIdf { get; set; }
    
        public virtual GiftedPerson GiftedPerson { get; set; }
        public virtual User User { get; set; }
    }
}
